### ISSUE TITLE
功能建议：在浏览器缩小的时候，侧边栏收进去

### ISSUE THREAD

**Issue by TheBlindM** [honghuangdc/soybean-admin#109]
在浏览器缩小的时候，侧边栏收进去，而不是手动去点

![image](https://user-images.githubusercontent.com/48701152/176608313-2afdda64-390d-4f0e-9d93-f3b61ccf52bf.png)

![image](https://user-images.githubusercontent.com/48701152/176608288-27ff4dc9-51fb-4da7-8944-519e619ee4ef.png)

**Comment by honghuangdc** [comment]
这个需要适配移动端，后面再考虑吧 #87
