### ISSUE TITLE
tab bug

### ISSUE THREAD

**Issue by kenixFog** [honghuangdc/soybean-admin#111]
![2022-07-11 09-03-43](https://user-images.githubusercontent.com/29566225/178170496-bda6f822-b88d-42a9-a30f-12a3c5f29d15.jpg)

win11 

Microsoft Edge
版本 103.0.1264.49 (正式版本) (64 位)

**Comment by honghuangdc** [comment]
嗯嗯，这个问题我看到了，晚点我修复下
