### ISSUE TITLE
如何贡献

### ISSUE THREAD

**Issue by snowords** [honghuangdc/soybean-admin#115]
我看到这个项目后比较感兴趣，想要参与进来一起推进开发进度，请问如何贡献？有没有功能认领或者开发安排？

**Comment by honghuangdc** [comment]
首先fork一下项目到自己的仓库里面，然后克隆仓库，切出一个新分支，在新分支上开发，推送，然后提交Pull Request

**Comment by honghuangdc** [comment]
到我的仓库来提Pull Request
