### ISSUE TITLE
底部布局插槽

### ISSUE THREAD

**Issue by zhangke1722** [honghuangdc/soybean-admin#118]
现在页面布局不好处理底部悬浮按钮操作,如果在页面中用样式写好底部悬浮操作栏 ,进入页面时因为有动画会跳动一下,看是否能在增加一个底部插槽 ,对于实际业务中开发经常会用到, 效果参考 vben-admin高级表单页面    https://vvbin.cn/next/#/page-demo/form/high

![image](https://user-images.githubusercontent.com/20833460/183599461-23953eab-b271-4d6e-aae5-4cf4d6465ee3.png)

**Comment by honghuangdc** [comment]
可以在页面最外层加个h-full占满剩余高度，这样再弄一个底部的div放置按钮就行，上面的部分填充剩余高度，超出就滚动

**Comment by zhangke1722** [comment]
嗯 现在就是这样弄的  不过有些场景 在不撑开上方区域的时候也需要悬浮

**Comment by zhangke1722** [comment]
> 可以在页面最外层加个h-full占满剩余高度，这样再弄一个底部的div放置按钮就行，上面的部分填充剩余高度，超出就滚动

**Comment by zhangke1722** [comment]
嗯,现在就是这样弄的,不过有些场景 在不撑开内容空间的时候也要需要悬浮,这样就不太好处理了

**Comment by zhangke1722** [comment]
> 可以在页面最外层加个h-full占满剩余高度，这样再弄一个底部的div放置按钮就行，上面的部分填充剩余高度，超出就滚动

嗯,现在就是这样弄的,进来页面底部悬浮就会跳动一下,有一个默认padding 16的关系还有貌似应该是动画的关系,而且有些场景 在不撑开内容空间的时候也要需要悬浮,这样就不太好处理了
