### ISSUE TITLE
滚动条页面刚进来的时候页面抖动

### ISSUE THREAD

**Issue by zhangke1722** [honghuangdc/soybean-admin#119]
https://soybean.pro/#/component/button  在页面切换时,对于页面超过一屏有滚动条的,页面内容会因为滚动条的出现,页面宽度变化抖动下

**Comment by honghuangdc** [comment]
后面可能会引入滚动条插件来优化这个

**Comment by Wyatex** [comment]
希望能做成body是100vh，如果然后页面内容部分做成overflow: auto，解决顶部栏一直在动的问题，说实话我个人感觉挺难受的
