### ISSUE TITLE
动态权限路由

### ISSUE THREAD

**Issue by yanbowe** [honghuangdc/soybean-admin#12]
动态权限路由什么时候做呀，想看看作者思路。

**Comment by yanbowe** [comment]
或者我提个pr，但可能没有作者思路好

**Comment by honghuangdc** [comment]
咱可以加个微信聊一下，你可以先分享一下你的思路。
微信号 honghuangdc

**Comment by yanbowe** [comment]
> 咱可以加个微信聊一下，你可以先分享一下你的思路。 微信号 honghuangdc

好的

**Comment by kungege** [comment]
哈喽，请问有计划实现了吗？我正在用这个做后台管理系统，动态路由是不可或缺的一部分，十分感谢你们的工作！

**Comment by honghuangdc** [comment]
> 哈喽，请问有计划实现了吗？我正在用这个做后台管理系统，动态路由是不可或缺的一部分，十分感谢你们的工作！

最近这几天有空准备着手这个功能

**Comment by honghuangdc** [comment]
已实现基于mock的动态权限路由，下一版上线
