### ISSUE TITLE
建议移除对lodash的依赖

### ISSUE THREAD

**Issue by ugrg** [honghuangdc/soybean-admin#126]
我分析了代码中关于lodash的依赖代码，只使用了两个地方：
1.cloneDeep 应用于 theme的合并，
```
// src/store/modules/theme/helpers.ts
  const otherColor = { ...themeSetting.otherColor, info };
  const setting = cloneDeep({ ...themeSetting, themeColor, otherColor });
  return setting;
```
从对象结构上来看，这里完全可以使用`JSON.parse(JSON.stringify({ ...themeSetting, themeColor, otherColor }))`的方式来实现。
不仅如此，在我查阅了所有代码后发现initThemeSettings也只是在初始化`theme-store`时被调用了一次，完全可以不做深拷贝也不影响功能。所以这里我建议直接移除cloneDeep,改成
```
  const setting = { ...themeSetting, themeColor, otherColor };
```
2. kebabCase 应用于 添加css vars至html
```
// src/store/subscribe/theme.ts
/** 添加css vars至html */
function addThemeCssVarsToHtml(themeVars: ThemeVars) {
  const keys = Object.keys(themeVars) as ThemeVarsKeys[];
  const style: string[] = [];
  keys.forEach(key => {
    style.push(`--${kebabCase(key)}: ${themeVars[key]}`);
  });
  const styleStr = style.join(';');
  document.documentElement.style.cssText += styleStr;
}
```
这里kebabCase主要作用是命名格式转换，此函数可以使用如下代码代替，可以考虑在`src/utils/common`目录下添加`string.ts`来定义该函数。
```
const K_C_MATCH = /[A-Z]{2,}(?=[A-Z][a-z]+\d*|\b)|[A-Z]?[a-z]+\d*|[A-Z]|\d+/g;
/**
 * 转换为短横拼写法
 * @param {string} str
 * @returns {string}
 */
export const kebabCase = (str: string) =>
  str
    .match(K_C_MATCH)!
    .map(x => x.toLowerCase())
    .join('-');
```
写在最后：
lodash是一个不错的工具，但在这个项目中，我们仅使用了他不到1%的功能，但缺要依赖他的完整包，实在有点不划算，建议移除对他的依赖。

**Comment by honghuangdc** [comment]
lodash-es是tree-shake的，你可以在.env.production 将VITE_VISUALIZER改成Y, 然后打包一下，打包后的stats.html能找到lodash-es占据的体积rendered 93.86kb，gzip和brotli都是40级kb多
