### ISSUE TITLE
[需求]更多场景下的权限和菜单模式

### ISSUE THREAD

**Issue by chenwen97** [honghuangdc/soybean-admin#135]
作者你好，我查阅文档和代码之后发现，当前的权限模式是固定的前端角色权限。

后期是否考虑添加更多的权限处理方式呢？如果权限是动态的，需要如何处理呢，后期是否考虑优化。

这是我在另一个项目中看到的处理方式，可以参考一下https://vvbin.cn/doc-next/guide/auth.html

最后补充一下，你的代码写的很优雅，项目UI也很美观，我非常喜欢，感谢你对开源做出的贡献

**Comment by honghuangdc** [comment]
目前的权限路由这一块是分为前端的static模式和后端的dynamic模式，dynamic模式直接由后端返回相应用户对应权限的路由的

**Comment by honghuangdc** [comment]
感谢支持😊

**Comment by yyqxjwxy** [comment]
> 目前的权限路由这一块是分为前端的static模式和后端的dynamic模式，dynamic模式直接由后端返回相应用户对应权限的路由的

可不可以既有静态也有动态的路由

**Comment by honghuangdc** [comment]
> 

将需要作为静态路由的数据放到constantRoutes里面，src/router/routes/index.ts

**Comment by shabby2333** [comment]
我这边的处理是 路由前台配置，权限后台配置
然后把权限改成一对多(1用户 - 1角色 - 多权限)
后台只管理权限，通过权限控制路由

缺点就是 后台只能通过前台代码里写死权限去配置路由显隐

**Comment by shabby2333** [comment]
> 我这边的处理是 路由前台配置，权限后台配置 然后把权限改成一对多(1用户 - 1角色 - 多权限) 后台只管理权限，通过权限控制路由
> 
> 缺点就是 后台只能通过前台代码里写死权限去配置路由显隐

这个处理方式主要是由于我个人认为路由mapping到地址这一步 因为是死的 没什么不发版热更调整路由映射的需求
但是有通过后台控制权限组权限范围的需求
加上重构之前的系统，权限是一对多的，所以选用了这个处理思路（之前的轮子 路由也是后端配置，动态拉，我废弃了）
