### ISSUE TITLE
[需求] 主题配置增加保存配置功能

### ISSUE THREAD

**Issue by XTeam-Wing** [honghuangdc/soybean-admin#136]
<img width="364" alt="image" src="https://user-images.githubusercontent.com/25416365/192676148-15b9af32-05fd-49a6-8fb7-45cd9cc9a87a.png">

现在将主题切换到暗黑模式之后，刷新浏览器或者打开新的窗口就会复原，可以将配置保存在用户的浏览器中。

**Comment by honghuangdc** [comment]
本地开发模式是不缓存配置的，生产环境目前是缓存配置的

**Comment by honghuangdc** [comment]
因为本地开发模式要调整主题得让用户感知到，所以用户得主动去更改theme.json

**Comment by XTeam-Wing** [comment]
> 

我pnpm build之后部署，更换主题之后没缓存。
编译的时候有什么注意事项吗。QAQ

**Comment by honghuangdc** [comment]
缓存是放到浏览器里面的，不同环境的主题当然不能保证统一
