### ISSUE TITLE
tab页(多页签)很多时无法左右滚动，无法定位到前面的tab页

### ISSUE THREAD

**Issue by zhouxx** [honghuangdc/soybean-admin#137]
如题，要么是左右滚动，可以找到相关的页签，要么像chrom一样，出一个下拉，可以选到已经打开的页签。
![image](https://user-images.githubusercontent.com/9975353/193378548-f8333082-cc35-4b9f-940c-e63e1d28212a.png)

**Comment by honghuangdc** [comment]
可以左右滚动，直接左右拖拽就行了

**Comment by zhouxx** [comment]
好的，确实可以，不过隐藏地比较深，哈哈
