### ISSUE TITLE
目前看项目的路由最终都是转换为二级路由，那么三级活以上路由的公共compoent 如何设置

### ISSUE THREAD

**Issue by Miofly** [honghuangdc/soybean-admin#144]
如题，二级路由目前有公共的 layout 组件，有个业务场景是，有一些三级路由页面需要有一个公共的 layout 这种在全部转换为二级路由的情况下是否无法通过 routev-view 实现了，还有就是为什么要把路由全部转换为二级路由，这样做有什么好处吗？

**Comment by honghuangdc** [comment]
这里所谓的多级路由，实际上是菜单上衍生出来的多层级路由，它们实际上只有一个公共的layout，转换成二级路由的数据是为了缓存页面

**Comment by honghuangdc** [comment]
业务上基本上都可以通过二级路由表示的，要么你说的是一个页面上又有不同的模块，这些模块又共用一些组件
