### ISSUE TITLE
VsCode提示`RouterPage`命名空间不存在

### ISSUE THREAD

**Issue by Wangijun** [honghuangdc/soybean-admin#146]
![image](https://user-images.githubusercontent.com/40266995/201503223-ea30f947-fe64-4d85-b1f8-4441bbcdeefd.png)

**Comment by Wangijun** [comment]
已经安装过依赖。

**Comment by honghuangdc** [comment]
pnpm dev启动一下项目，会自动生成 router-page.d.ts声明文件
