### ISSUE TITLE
重置路由时，需要刷新下页面，不然不会跳转到登录页面

### ISSUE THREAD

**Issue by noobHuKai** [honghuangdc/soybean-admin#152]
问题：
刷新`token` 接口失效的话，跳转不到登录页面，会直接跳转到 `404`
复现：
登录后，使`token`,`refreshToken` 都过期
原因：
当 `token` 失效时，会刷新 `token`。如果都失效的话，会跳转到登录页面，重置`auth`状态。`src\store\modules\auth\index.ts` 里面 `resetAuthStore` 函数
解决方法：
需要在 `src\store\modules\route\index.ts` 里  `resetRouteStore` 函数中加上刷新页面语句，如 `router.go(0);` 
```
  /** 重置路由的store */
    resetRouteStore() {
      this.resetRoutes();
      this.$reset();
      // 刷新页面，不然不会加载
      router.go(0);
    },
```

**Comment by noobHuKai** [comment]
这样又会导致在退出登录的时候刷新下页面，

**Comment by honghuangdc** [comment]
已修复
