### ISSUE TITLE
VSCode 提示属性不对

### ISSUE THREAD

**Issue by johums-best** [honghuangdc/soybean-admin#154]
看了 package.json 
设置了：    "typecheck": "vue-tsc --noEmit --skipLibCheck",
但是还是提示有问题。
在git cz 提交时候也会提示报错

<img width="766" alt="image" src="https://user-images.githubusercontent.com/60348756/203313373-763e815e-2d81-4f7e-ba0b-951f5953db1c.png">
<img width="800" alt="image" src="https://user-images.githubusercontent.com/60348756/203313535-37f790c1-9dad-49b7-9d4f-fadbe73e5c05.png">

**Comment by honghuangdc** [comment]
试试以下的方法：
1.安装vue的插件volar
2.重启一下TS服务器 查看 => 命令面板 => 输入 TypeScript  => 点击 Restart TS server

**Comment by johums-best** [comment]
> 试试以下的方法： 1.安装vue的插件volar 2.重启一下TS服务器 查看 => 命令面板 => 输入 TypeScript => 点击 Restart TS server

重新试了一下也是不行，然后 volar 是有安装的
下图是我执行 git cz 产生的报错的

<img width="1008" alt="image" src="https://user-images.githubusercontent.com/60348756/203567359-9d314617-1400-48af-9821-0afb50536059.png">
