### ISSUE TITLE
使用输入框时，字符包含下划线时，不显示下划线

### ISSUE THREAD

**Issue by sunyuanonly** [honghuangdc/soybean-admin#162]
![image](https://user-images.githubusercontent.com/16498201/206132776-1bff26bb-3725-4036-864f-0284f92a7de5.png)

**Comment by SunYuanOnly** [comment]
@honghuangdc

**Comment by honghuangdc** [comment]
是什么浏览器，我这边是正常的

**Comment by SunYuanOnly** [comment]
Microsoft Edge 版本 108.0.1462.42 (正式版本) (64 位)

**Comment by SunYuanOnly** [comment]
> 好像是显示器的原因，在笔记本上是正常的，用的PHILIPS显示器不显示..........

但看官网的是正常的.... 就很奇怪
