### ISSUE TITLE
Replace `↹` with `··`

### ISSUE THREAD

**Issue by JOECHAN890** [honghuangdc/soybean-admin#164]
大佬,请问这个怎么解决,一格式化就提示这个错误,感谢!
[{
	"resource": "/e:/Test/soybean-admin/build/utils/index.ts",
	"owner": "eslint",
	"code": {
		"value": "prettier/prettier",
		"target": {
			"$mid": 1,
			"external": "https://github.com/prettier/eslint-plugin-prettier#options",
			"path": "/prettier/eslint-plugin-prettier",
			"scheme": "https",
			"authority": "github.com",
			"fragment": "options"
		}
	},
	"severity": 8,
	"message": "Replace `↹` with `··`",
	"source": "eslint",
	"startLineNumber": 8,
	"startColumn": 1,
	"endLineNumber": 8,
	"endColumn": 2
}]

**Comment by honghuangdc** [comment]
格式化的配置没有配置好，你看一下是不是开启了保存就自动用编辑器的格式化， "editor.formatOnSave": false,就是这个配置需要设置成false

**Comment by honghuangdc** [comment]
项目里面已经配置好了eslint + prettier的格式化，不用再借助编辑器的格式化，不然会造成冲突的
