### ISSUE TITLE
组件都是用index.vue 命名，不利于调试

### ISSUE THREAD

**Issue by wflixu** [honghuangdc/soybean-admin#165]
使用vue tools 工具调试，全是index.vue, 根本分不清是那个组件，还要通过class 辨别。
另外编辑的时候，也是满页签的index.vue, 不利于找到要编辑的组件

**Comment by honghuangdc** [comment]
vue devtools调试可以通过点击页面来匹配对应的组件

vscode编辑器可以通过 cmd + P 全局查找文件

**Comment by wzc520pyfm** [comment]
项目引入了VueMacros，在setup中使用defineOptions({ name: "ComponentName" });即可配置组件名，便于在vue devtools中调试。
