### ISSUE TITLE
动态路由模式下的排序问题

### ISSUE THREAD

**Issue by soup-Lee** [honghuangdc/soybean-admin#168]
您好！我在学习您的路由系统的时候发现了一个问题，当模式设置为动态路由时，路由系统并未对路由进行排序处理，我注意到mock的model内您是有保留order的属性的，所以猜想这块是否有所遗漏？
如果这真的是一个问题的话，我觉得可以从以下的两点进行优化
1、将src/utils/router/models内的sortRoutes函数进行导出
2、在src/store/modules/route/index内的第122行（即在initDynamicRoute函数内将返回的data.routes传入handleAuthRoute处）为data.routes进行sortRoutes处理
经过我的测试这个方法是可行的，如果您觉得这符合优雅的话，我非常愿意得到一次提pr的机会哈哈哈哈哈

**Comment by honghuangdc** [comment]
可以的👍，欢迎贡献！

**Comment by honghuangdc** [comment]
#169
