### ISSUE TITLE
[需求] 希望可以增加文件上传，图片剪切组件实例

### ISSUE THREAD

**Issue by yaoysyao** [honghuangdc/soybean-admin#183]
希望可以增加文件上传，图片剪切组件实例

**Comment by CracKerMe** [comment]
文件上传 一般公司UI定制程度很高，自己根据 upload UI组件去改 或者 input 去魔改实现

图片裁切可以考虑使用 https://cropper.chengpeiquan.com/zh/

**Comment by honghuangdc** [comment]
上传可以用这个库：https://github.com/transloadit/uppy

**Comment by honghuangdc** [comment]
需求意愿等级不高，可以安排到2.0 #188
