### ISSUE TITLE
[需求] 这个顶部菜单模式，菜单很多的情况能不能处理一下

### ISSUE THREAD

**Issue by West121** [honghuangdc/soybean-admin#185]
![image](https://user-images.githubusercontent.com/29170680/220867174-73f66e99-5e0c-45d7-85ab-bad038cbeac3.png)
![image](https://user-images.githubusercontent.com/29170680/220867612-06cc912b-c9d0-43ca-9e92-9fc4ff553a03.png)

**Comment by honghuangdc** [comment]
有时间我实现一下

**Comment by honghuangdc** [comment]
安排在1.0版本实现 #172
