### ISSUE TITLE
弱弱的问一个问题，怎么把所有示例菜单放到一个目录里去

### ISSUE THREAD

**Issue by West121** [honghuangdc/soybean-admin#186]
添加路由，修改路由怎么操作呢？这个插件文档也有没有介绍“@soybeanjs/vite-plugin-vue-page-route”，效果类似于这样：
![image](https://user-images.githubusercontent.com/29170680/221414482-c6190f17-95e5-4886-b31f-2c58a83f9535.png)

**Comment by honghuangdc** [comment]
按照_builtin这个文件夹的命名方法

**Comment by honghuangdc** [comment]
这个插件 @soybeanjs/vite-plugin-vue-page-route 有个 routeNameTansformer的属性，默认 以下划线“_”开头的文件夹在转化时不会在路由名称中

**Comment by honghuangdc** [comment]
添加路由和修改路由就正常建立文件夹和页面文件index.vue，然后会自动生成对应的类型、文件导入和路由模块定义，接口再根据自己的需求，去变更路由模块的数据。
