### ISSUE TITLE
需求建议

### ISSUE THREAD

**Issue by nodeds** [honghuangdc/soybean-admin#187]
1. 手机端 模式下, 顶部菜单模式, 就无法显示
2. 可否增加一个锁屏的功能, 类似官网那样
3. 用户管理 表格, 左侧增加一个 列表用户分组管理, 类似联动那种效果

**Comment by honghuangdc** [comment]
1.手机端对于菜单的显示只有侧边菜单栏相对合适，最近正好再会上新的布局组件，到时候会在逻辑上做个限制，移动端就只有特定的布局 #172 
2.锁屏功能需求意愿等级不高，考虑在1.0发布后再安排，另外官网没看到锁屏组件 #188 
3.用户管理之类的都是偏向业务，需求意愿等级不高 #188
