### ISSUE TITLE
更加灵活的路由组织

### ISSUE THREAD

**Issue by yingnian** [honghuangdc/soybean-admin#190]
<img width="885" alt="image" src="https://user-images.githubusercontent.com/22848458/221722679-b2cafdfd-5269-49d5-bbf4-52a32413a5ed.png">

**Comment by honghuangdc** [comment]
1.第一个暂时无解，因为菜单的数据是根据路由来的
2.第二个目前可以用 多个路由文件复用一个组件的形式，路由插件后面考虑支持更多能力，如支持路径参数的路由，还有这个一个文件对应多个路由 #188
