### ISSUE TITLE
lang="tsx"的文件中定义变量后删除变量加载不出内容

### ISSUE THREAD

**Issue by maddenBoy** [honghuangdc/soybean-admin#201]
### 例如在 src/views/component/table/index.vue，定义新一个变量，保存后，此时页面可以正常加载新添加的变量
![image](https://user-images.githubusercontent.com/71129660/223599678-15564380-c1fa-4ebd-952b-6d74b5583ba9.png)
### 把定义的变量删除，保存后，此时，若点击侧边栏的任意界面均无法显示对应内容，需要刷新浏览器或重启vite
![image](https://user-images.githubusercontent.com/71129660/223600072-713c758e-c5bf-4498-92c3-5c8036ea4b6f.png)
大佬知道怎么解决吗？
![image](https://user-images.githubusercontent.com/71129660/223600665-78bdc9c7-f0e1-4a5c-9bd0-3b90592bb65d.png)

**Comment by honghuangdc** [comment]
我这边测试了下，没有你说的情况

**Comment by maddenBoy** [comment]
> 我这边测试了下，没有你说的情况
可以看下复现录屏
[QQ录屏20230308123336.webm](https://user-images.githubusercontent.com/71129660/223620808-a2e71753-87c9-46c7-b341-c67a786bf27f.webm)

**Comment by honghuangdc** [comment]
这个问题有可能是Vite热更新导致的路由数据丢失

**Comment by honghuangdc** [comment]
其他项目有遇见过类似的问题吗

**Comment by maddenBoy** [comment]
其他项目好像会报错，应该是vite使用tsx时热更新的bug

**Comment by honghuangdc** [comment]
等vite修复自己的热更新
