### ISSUE TITLE
使用pnpm i 时，安装到core-js-pure@3.29.0就报错了，不知道是那里出了问题

### ISSUE THREAD

**Issue by preBall** [honghuangdc/soybean-admin#202]
这是报错警告
![图片](https://user-images.githubusercontent.com/87239510/224239686-36db0118-dfba-4c5c-9465-8e1761ede75a.png)
nodejs是 v16.19.1，pnpm是7.29.1，都是符合要求的，一直卡在这里，麻烦看下到底是那里出错了。

**Comment by honghuangdc** [comment]
把你的文件夹Git_Clone改成GitClone或者git-clone，删除node_module，pnpm-lock.yaml，再安装一下依赖，看看这样行不

**Comment by preBall** [comment]
![image](https://user-images.githubusercontent.com/87239510/224359961-925ff9fe-0227-45f4-974e-8b2e0475335d.png)
好像没有什么作用

**Comment by preBall** [comment]
> 把你的文件夹Git_Clone改成GitClone或者git-clone，删除node_module，pnpm-lock.yaml，再安装一下依赖，看看这样行不

好像没什么用
![image](https://user-images.githubusercontent.com/87239510/224361869-655120d9-8d77-4cac-9bf4-ecce0092b23a.png)

**Comment by honghuangdc** [comment]
你这是windows的，项目放到D盘，不要放到C盘，会有很多权限问题

**Comment by preBall** [comment]
> 你这是windows的，项目放到D盘，不要放到C盘，会有很多权限问题

这个应该和权限没什么关系，我也放到过其它盘试过，不过现在我用linux运行项目倒是没什么问题了
