### ISSUE TITLE
基于soybean-admin 二次开发的开源项目 electron-mock-admin

### ISSUE THREAD

**Issue by lixin59** [honghuangdc/soybean-admin#203]
## 简介

帮助前端开发伙伴快速实现接口的mock

[electron-mock-admin](https://github.com/lixin59/electron-mock-api) 是一个Mock Api 管理系统
## 下载地址
[下载](https://github.com/lixin59/electron-mock-api/releases) 是一个Mock Api 管理系统

## 效果展示

![image](https://user-images.githubusercontent.com/57742124/224279816-cd6cdf8f-7efd-433f-8397-fb2a7c84ba0a.png)
![image](https://user-images.githubusercontent.com/57742124/224279895-700df8e1-512a-410b-8a4a-ec7a6f339eec.png)
![image](https://user-images.githubusercontent.com/57742124/224280268-7d6a7b68-0193-4fdf-9e8b-d90a2eae25c8.png)
![image](https://user-images.githubusercontent.com/57742124/224280556-700549c9-9c53-45ba-ac02-b81f546dd1cc.png)
![image](https://user-images.githubusercontent.com/57742124/224280784-04ceb504-e5f4-4b71-9c9b-8bc19506956b.png)

**Comment by honghuangdc** [comment]
已更新进README.md
