### ISSUE TITLE
简化设计

### ISSUE THREAD

**Issue by cityblack** [honghuangdc/soybean-admin#204]
看了一下路由的部分。说真的，有必要设计的这么复杂么。过度设计了未免。

**Comment by honghuangdc** [comment]
每个人跟你一样都提个想法，那这个系统不久乱套了

**Comment by honghuangdc** [comment]
再说了，我这个设计你能看得懂的吗，talk is cheap, show me your code.

**Comment by cityblack** [comment]
这个应该是怎么使用简单这么来吧。。参考[PanJiaChen](https://github.com/PanJiaChen)的设计好吧。 另外，什么自信？觉得自己天才设计？真的有点服气。。能被人吐槽还觉得自己设计的很完美？

**Comment by cityblack** [comment]
而且都已经把设计思路讲出来，还 show me your code?

**Comment by honghuangdc** [comment]
我TM辛辛苦苦花了那么长时间开发出来的东西就因为你的一两句话就改了，你谁呀

**Comment by honghuangdc** [comment]
别再在刷存在感，不喜欢就不要用我开发的东西

**Comment by cityblack** [comment]
哦~ 你这意思，合不合理不重要，重要写出来就行了？ 得，索性关闭掉吧，连看法都不能提，牛逼

**Comment by honghuangdc** [comment]
说了不要在这刷存在感了，拿出你的资本实力来，不要在这做最强嘴炮
