### ISSUE TITLE
是否考虑解决依赖循环问题

### ISSUE THREAD

**Issue by zam157** [honghuangdc/soybean-admin#207]
我用[dependency-cruiser](https://github.com/sverweij/dependency-cruiser)分析了一下项目发现了这些循环依赖问题
![image](https://user-images.githubusercontent.com/24277775/225165963-b8312cf5-9430-40f0-a036-b2ac5f1c4d06.png)

由于Vite一直不能很好地解决循环依赖的热更新问题，随着项目规模不断增长可能热更新会有[问题](https://cn.vitejs.dev/guide/troubleshooting.html#a-full-reload-happens-instead-of-hmr)，隔壁vben就深陷[其中](https://github.com/vbenjs/vue-vben-admin/issues?q=%E7%83%AD%E6%9B%B4%E6%96%B0)（热更新巨慢，随便修改一个文件很容易就引发full page reload）

因为趟过这个坑所以想提醒一下

**Comment by honghuangdc** [comment]
感谢你的建议，估计是我在很多文件夹里面的index文件做了统一的导出才会这样的，我有空分析一下看看怎么解决好，或者你有好的解决方法，可以提个PR

**Comment by zam157** [comment]
> 感谢你的建议，估计是我在很多文件夹里面的index文件做了统一的导出才会这样的，我有空分析一下看看怎么解决好，或者你有好的解决方法，可以提个PR

抱歉，我暂时也没有太好的解决办法，属于是还在坑里爬的阶段😢 有空我也会尝试一下解决

**Comment by honghuangdc** [comment]
#188 v2.0再解决这个问题
