### ISSUE TITLE
[Bug]: 响应拦截器可以优化仔细点？？？

### ISSUE THREAD

**Issue by Fluox-Etine** [honghuangdc/soybean-admin#209]
### 软件版本

0.9.9

### 运行环境

MacOS

### 运行架构

x86

### 重现步骤

你好我这边有一个疑问就是 既然后端返回错误状态码回来了，为啥调用接口的地方还能往下执行呢？？？既然拦截器拦截到错误信息；就应该不往下执行？？？

### 期望的结果是什么？

拦截到错误信息。调用的地方不能往下执行。避免二次重复判断数据

### 实际的结果是什么？

拦截器只是提示了错误信息。还在继续执行

**Comment by yanbowe** [comment]
这属于正常逻辑，你应该在调用接口的时候增加错误状态码判断。

**Comment by honghuangdc** [comment]
你这个问题得有上下文：
1. 请解释下“为啥调用接口的地方还能往下执行”，用相关的代码示例说明
2. 后端的业务上的错误得自己加逻辑进行处理
