### ISSUE TITLE
.vscode的一些非必要设置

### ISSUE THREAD

**Issue by beiyanpiki** [honghuangdc/soybean-admin#21]
很好的demo！
提个小建议，可以把.vscode的一些非必要设置删掉（比如 ``workbench.iconTheme``）或者直接把文件夹ignore掉，第一次打开以为自己vscode坏了🤣🤣🤣。

**Comment by honghuangdc** [comment]
这个配置是需要安装material-icon-theme插件的，这个是个文件夹和文件的图标主题，对区分不同文件夹很有帮助

**Comment by beiyanpiki** [comment]
push到仓库的代码里面放个人配置文件我觉得并不是一个好的选择，只是个人小建议，不管也没事哈哈
