### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by taisha** [honghuangdc/soybean-admin#212]
### 软件版本

不限制

### 运行环境

Windows (64)

### 运行架构

None

### 重现步骤

如果仓库的 `.git` 文件夹不在 `soybean-admin` 根目录下, 则 git 的 commit 指令无法正确执行。
原因是 `.git/hooks` 下的指令的执行路径是 `.git` 所在的目录，这样  `pnpm soy git-commit-verify` 找不到 "soybean-admin\package.json". 
如果手动修改 `.git/hooks` 下的指令为  `cd soybean-admin && pnpm soy git-commit-verify`，则能够正常工作。

### 期望的结果是什么？

即便 `.git` 文件夹不在 `soybean-admin` 根目录下，也能够正确执行 `pnpm commit` 指令。这可能需要修改 soybean-cli 的代码。

### 实际的结果是什么？

如果仓库的 `.git` 文件夹不在 `soybean-admin` 根目录下, 则 git 的 commit 指令无法正确执行。

**Comment by honghuangdc** [comment]
特殊环境特殊处理

**Comment by dodu2014** [comment]
同样的问题，在其他目录名称下 commit 不可用，怎么修改可用 @taisha @honghuangdc
