### ISSUE TITLE
[Bug]: 目前刷新方案存在缺陷

### ISSUE THREAD

**Issue by maddenBoy** [honghuangdc/soybean-admin#213]
### 软件版本

main

### 运行环境

Windows (64)

### 运行架构

None

### 重现步骤

# 对于keep-alive缓存的页面，重新加载按钮的刷新方案有缺陷，点击reloadButton刷新时，再次加载时pinia定义的数据不会被重置，如果把重置操作定义在onDeactivated或onActivated中，那么，切换tabs时也会触发重置操作。代码中点击reloadButton刷新先移除缓存再加回去并无法使组件执行正常的生命周期。
## 1、先在app-store中定义一个test变量，如下图
![image](https://user-images.githubusercontent.com/71129660/232228301-31a3f8f5-2740-439c-8012-f7257838427a.png)
##  2、在about页面写一个input组件，绑定app-store中的test变量，input随便输入一下内容
![image](https://user-images.githubusercontent.com/71129660/232228246-35baf4c3-7c16-4a2b-a5f8-38e6d6f7c8e0.png)
## 3、点击reloadButton组件进行刷新，刷新后test变量不会被改变
![image](https://user-images.githubusercontent.com/71129660/232228589-3f57ece5-227c-47bf-b694-0a4d4b7dc7c3.png)
## 4、下面刷新时移除缓存路由再加回去的代码时似乎是无效的代码
![image](https://user-images.githubusercontent.com/71129660/232227950-a74a6bac-2f16-4b9b-86c9-e8e1da53e4e1.png)

### 期望的结果是什么？

 对于keep-alive缓存的页面，点击reloadButton或右键页签重新时，再次加载时pinia定义的数据被重置，而切换tabs时不触发重置操作。

### 实际的结果是什么？

 对于keep-alive缓存的页面，点击reloadButton或右键页签重新时，再次加载时pinia定义的数据不会被重置

**Comment by honghuangdc** [comment]
你自己理解一下什么叫全局状态

**Comment by maddenBoy** [comment]
为什么点击刷新按钮，不能达到和像F5刷新页面一样的效果呢？刷新不会重置全局状态数据不是又问题吗？

**Comment by maddenBoy** [comment]
别的系统采用跳转空白页，再重定向回当前路由地址的方案，全局状态的数据是会被重置的，感觉这种才跟刷新页面效果一致，只不过这种方案url地址会闪一下
