### ISSUE TITLE
[Bug]:  每次运行会删除我修改的路由配置

### ISSUE THREAD

**Issue by JanYork** [honghuangdc/soybean-admin#218]
### 软件版本

最新

### 运行环境

Windows (64)

### 运行架构

None

### 重现步骤

page-route.d.ts新增了RouteKey的内容，pnpm run dev 后会自动删除我定义的内容。

### 期望的结果是什么？

不会删除我修改的内容

### 实际的结果是什么？

每次pnpm run dev后，我定义的路由全会被还原，删除我新增的路由key

**Comment by honghuangdc** [comment]
page-route.d.ts是自动生成的，不用手动维护, 把路由模式切换成static模式
