### ISSUE TITLE
[Bug]: tab-reload

### ISSUE THREAD

**Issue by kenixFog** [honghuangdc/soybean-admin#228]
### 软件版本

0.9.9

### 运行环境

Windows (64)

### 运行架构

x86

### 重现步骤

keepalive页面，点击tab的重新加载按钮，每点一次重新加载，请求会多重复发送一次。

比如有请求A，onmounted的时候执行，第一次进入页面，请求1次，点击重新加载，重复请求2次，再点一次重新加载，重复请求3次

### 期望的结果是什么？

请求1次

### 实际的结果是什么？

第N次点击重复加载，页面加载后，请求会重复执行N+1次

**Comment by kenixFog** [comment]
思考了下，感觉好像是getCacheRoutes这根据二级路由判断的问题~

**Comment by kenixFog** [comment]
另外，tab页，右键菜单的重新载入，对keepalive页面不生效~

**Comment by honghuangdc** [comment]
目前做的就是点击重新加载图标就会清除掉缓存的页面
