### ISSUE TITLE
你好，方便分享一下项目里的svg资源是在哪找的吗

### ISSUE THREAD

**Issue by xykjlcx** [honghuangdc/soybean-admin#23]
项目很好，学习到很多

想知道这么多好看的插画，是在哪里找的😂

**Comment by honghuangdc** [comment]
项目里面的403、404、500的插画： https://storyset.com/

**Comment by honghuangdc** [comment]
还有一些获取免费矢量图的网站：
https://www.freepik.com/
https://www.vecteezy.com/

**Comment by xykjlcx** [comment]
好的，谢谢老哥哈。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "honghuangdc/soybean-admin"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月8日(星期三) 下午4:46
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [honghuangdc/soybean-admin] 你好，方便分享一下项目里的svg资源是在哪找的吗 (Issue #23)





 
项目里面的403、404、500的插画： https://storyset.com/
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
