### ISSUE TITLE
为什么现在组件命名用的是 kebab-case 的方式了？

### ISSUE THREAD

**Issue by flyingfishzxf** [honghuangdc/soybean-admin#231]
看文档里面描述文件路径的时候，还看到是用的 PascalCase 的形式，但是源码已经变成了 kebab-case 了，我在常见问题关于组件命名里看到的也是要求用 PascalCase 形式命名组件，怎么实际上却是 kebab-case 了呢？困扰我的地方在于，我个人也是习惯使用 PascalCase 命名组件，现在看到 kebab-case 有点不习惯，所以好奇问一问，谢谢。

**Comment by honghuangdc** [comment]
文档里面的是之前的伙伴帮忙完善的，在文件命名这一块为了避免大小写不敏感的问题都统一为kebab-case方式了
