### ISSUE TITLE
[Bug]: 跑起来了，打开网页白屏

### ISSUE THREAD

**Issue by a-goer** [honghuangdc/soybean-admin#239]
### 软件版本

0.99

### 运行环境

Windows (64)

### 运行架构

None

### 重现步骤

pnpm dev  跑起来了打开网页一片空白

### 期望的结果是什么？

？

### 实际的结果是什么？

？

**Comment by honghuangdc** [comment]
请提供详细的运行环境，运行日志，保存信息等

**Comment by a-goer** [comment]
node 16.14.2

**Comment by a-goer** [comment]
![1685337006023](https://github.com/honghuangdc/soybean-admin/assets/43976630/4c5d5bf2-a50c-4e8d-a6be-ffb6c5939c36)

![image](https://github.com/honghuangdc/soybean-admin/assets/43976630/3370d9d1-9314-4170-8aeb-6873d2be1f9d)

**Comment by honghuangdc** [comment]
> 
> ![1685337006023](https://github.com/honghuangdc/soybean-admin/assets/43976630/4c5d5bf2-a50c-4e8d-a6be-ffb6c5939c36)
> 
> ![image](https://github.com/honghuangdc/soybean-admin/assets/43976630/3370d9d1-9314-4170-8aeb-6873d2be1f9d)
> 

浏览器的控制台有什么错误日志

**Comment by honghuangdc** [comment]
> > 
> > ![1685337006023](https://github.com/honghuangdc/soybean-admin/assets/43976630/4c5d5bf2-a50c-4e8d-a6be-ffb6c5939c36)
> > 
> > ![image](https://github.com/honghuangdc/soybean-admin/assets/43976630/3370d9d1-9314-4170-8aeb-6873d2be1f9d)
> > 
> 
> 浏览器的控制台有什么错误日志

是用的谷歌浏览器吗

**Comment by honghuangdc** [comment]
请按照文档上的给出的浏览器环境、nodejs环境等运行

**Comment by a-goer** [comment]
![image](https://github.com/honghuangdc/soybean-admin/assets/43976630/92d95c73-ae94-47c4-bcbe-31ccb9a5b776)

**Comment by honghuangdc** [comment]
> ![image](https://github.com/honghuangdc/soybean-admin/assets/43976630/92d95c73-ae94-47c4-bcbe-31ccb9a5b776)
> 

更新到最新的SoybeanAdmin版本，有个依赖需要更新
