### ISSUE TITLE
你好，方便问一下，我克隆你之前提交的版本 引入全局 scss配置没效果是怎么回事

### ISSUE THREAD

**Issue by q2419068625** [honghuangdc/soybean-admin#24]
比如： https://github.com/honghuangdc/soybean-admin/tree/e61ee32a88798923a3a444748fbee6e427c07ca7 这个版本
我在 global.scss 新增一个样式在其他地方使用不生效。
是为什么呢？
麻烦作者有时间解答一下，谢谢。

**Comment by yanbowe** [comment]
我刚才试了下是可以的，检查下div上是否添加了此class？

**Comment by q2419068625** [comment]
加上了 class ,但没有相关样式
