### ISSUE TITLE
[Bug]: 菜单错位

### ISSUE THREAD

**Issue by japy93** [honghuangdc/soybean-admin#241]
### 软件版本

Microsoft Edge 版本 113.0.1774.57 (正式版本) (64 位)

### 运行环境

Windows (64)

### 运行架构

x86

### 重现步骤

1. 布局模式-左侧菜单混合
2. 菜单栏-折叠状态
3. 国际化-非中文

![screenshot20230531](https://github.com/honghuangdc/soybean-admin/assets/49198593/5b852a7d-0285-4928-a0ae-c42ced95b3b5)

### 期望的结果是什么？

菜单栏正常显示

### 实际的结果是什么？

菜单栏错位

**Comment by honghuangdc** [comment]
fixed in 5c085a1
