### ISSUE TITLE
[Bug]: 登录?redirect=xxxxx跳转没有权限的页面会404

### ISSUE THREAD

**Issue by heii** [honghuangdc/soybean-admin#242]
### 软件版本

0.10.1

### 运行环境

MacOS

### 运行架构

None

### 重现步骤

用管理员或普通用户登录
[https://soybean.pro/#/auth-demo/super](url)

### 期望的结果是什么？

当前权限用户的默认页

### 实际的结果是什么？

404

### 补充说明（可选）

或加个开关关掉这个功能

**Comment by honghuangdc** [comment]
在这里提及 #277
