### ISSUE TITLE
有没有请求的例子

### ISSUE THREAD

**Issue by liminjian1437** [honghuangdc/soybean-admin#25]
0.0 你这种写法 我看了半天 不知道请求要怎么写了

**Comment by honghuangdc** [comment]
在 service/api/demo 里面有两个示例：fetchDictionary、fetchDictionaryWithMiddleware
在页面上引入这两个函数
import { fetchDictionary, fetchDictionaryWithMiddleware } from '@/service;

async function testApi() {
  const { data: data1 } = fetchDictionary("管理熵");
  if(data1) {
    console.log(data1);
  }
  const { data: data2 } = fetchDictionaryWithMiddleware("管理熵");
  if(data2) {
    console.log(data2);
  }
}

testApi();

//按照上面的调用一下

**Comment by liminjian1437** [comment]
666 感谢🙏

**Comment by honghuangdc** [comment]
请求函数前面加个 await

**Comment by liminjian1437** [comment]
牛啊～ 可以了。我好好学习 下你的代码

**Comment by liminjian1437** [comment]
> 请求函数前面加个await

大佬还有个问题想请教下，如果有多个请求地址应该怎么改呢，还有怎么请求代理呢。

**Comment by liminjian1437** [comment]
> 请求函数前面加个await

大佬还有问题想请教下，如果有多个请求地址应该怎么改呢，还有怎么加请求代理呢。

**Comment by honghuangdc** [comment]
1. 在env.development 和 env.production 和env.staging里面添加一个新的请求地址
例如：VITE_HTTP_BAIDU_URL=https://www.baidu.com
2.在src/typings/env.d.ts 添加VITE_HTTP_BAIDU_URL: string;
3. 在src/service/request/index.ts 创建另一个request, 
例如: 
export const baiduRequest = createRequest({
  baseURL: import.meta.env.VITE_HTTP_BAIDU_URL,
  timeout: REQUEST_TIMEOUT
});
4. 再去api文件夹下创建对应业务的文件，引入baiduRequest即可

**Comment by honghuangdc** [comment]
代理的话，需要在vite.config.ts添加配置，参照文档：https://cn.vitejs.dev/config/#server-proxy

**Comment by liminjian1437** [comment]
> 1. 在env.development 和env.production 和env.staging里面添加一个新的请求地址
>    例如：VITE_HTTP_BAIDU_URL= https://www.baidu.com 
>    2.在src/typings/env.d.ts 添加VITE_HTTP_BAIDU_URL: string;
> 2. 在src/service/request/index.ts创建另一个请求，
>    例如：
>    export const baiduRequest = createRequest({ 
>    baseURL: import.meta.env.VITE_HTTP_BAIDU_URL, 
>    timeout: REQUEST_TIMEOUT 
>    });
> 3. 再去api文件夹下创建对应业务的文件，引入百度请求发酵

谢谢，说的很详细，看明白了。哈哈
