### ISSUE TITLE
feat：希望在tab栏中新增关闭全部tab、关闭左侧和关闭右侧功能

### ISSUE THREAD

**Issue by lhp0730** [honghuangdc/soybean-admin#257]
<img width="1890" alt="image" src="https://github.com/honghuangdc/soybean-admin/assets/51940708/64b10b4b-c8d2-4e1f-89e7-af934f5498be">

**Comment by xiaoriri-cloud** [comment]
右键tab栏有啊

**Comment by lhp0730** [comment]
好的，看到了。
