### ISSUE TITLE
新增一个组件，可能会导致其他页面白屏的问题

### ISSUE THREAD

**Issue by dodu2014** [honghuangdc/soybean-admin#259]
我在项目中增加了几个页面，其中一个第一次打开正常，之后会导致所有页面异常白屏，但控制台无任何警告或错误提示，能否看出来是哪的问题吗？
> 提示：此过程并无热更新

这是第一次进入后，页面正常的，控制台也无告警提示：
![image](https://github.com/honghuangdc/soybean-admin/assets/15245544/fa76b4bf-d67e-41dd-8382-3e78bc815f00)

然后再访问其他页面，就白屏了，其他所有页面都白屏，如下图所示：
![image](https://github.com/honghuangdc/soybean-admin/assets/15245544/3615d293-9614-403c-ad4c-f38e3c494388)

老大能否指导下可能会出现的问题呢

**Comment by dodu2014** [comment]
补充：如果不访问当前页面的情况下，其他页面切换时没有问题的。可控制台也无任何告警和错误提示。

**Comment by dodu2014** [comment]
可能表达不是太清楚，录制个 gif 给你看看

![动画](https://github.com/honghuangdc/soybean-admin/assets/15245544/64d55c86-9c39-4d6e-bbbe-d268a2c6cf0d)

**Comment by honghuangdc** [comment]
看一下是不是这个问题
https://docs.soybean.pro/faq/#tab-%E9%A1%B5%E7%AD%BE%E5%88%B7%E6%96%B0%E5%90%8E%E4%B8%80%E7%89%87%E7%A9%BA%E7%99%BD

**Comment by jiw0220** [comment]
[<Transition> 仅支持单个元素或组件作为其插槽内容。如果内容是一个组件，这个组件必须仅有一个根元素。](https://cn.vuejs.org/guide/built-ins/transition.html#the-transition-component)

**Comment by dodu2014** [comment]
@honghuangdc 确实，多了个注释行。非常谢谢~~~
