### ISSUE TITLE
[需求]: 能合一下精简版吗

### ISSUE THREAD

**Issue by zhangheng2022** [honghuangdc/soybean-admin#264]
### 软件版本

1.0.0

### 运行环境

Windows (64)

### 运行架构

None

### 重现步骤

能合一下精简版吗，谢谢了

### 期望的结果是什么？

能合一下精简版吗，谢谢了

### 实际的结果是什么？

能合一下精简版吗，谢谢了

**Comment by honghuangdc** [comment]
下个版本发布时会出的

**Comment by honghuangdc** [comment]
thin分支最新代码 # 685e0b50
