### ISSUE TITLE
[Bug]: routerPush更改当前页面参数时，onMounted会被再次执行

### ISSUE THREAD

**Issue by eAliwei** [honghuangdc/soybean-admin#266]
### 软件版本

v0.10.3

### 运行环境

Windows (64)

### 运行架构

None

### 重现步骤

```javascript
const router = useRouterPush();
router.routerPush({ name: 'system_users', query: getParams() as LocationQueryRaw });

onMounted(() => {
  console.log('onMounted');
});
```

### 期望的结果是什么？

当前页面onMounted只执行一次

### 实际的结果是什么？

routerPush每执行一次onMounted都会被触发

**Comment by honghuangdc** [comment]
为了支持同一个路由多个Tab，页面路由是以fullpath为key的，所以不同的查询参数会触发页面文件重新渲染
对于你来说，重新执行了onMounted也没问题，就相当于是刷新了页面一样

**Comment by flyingfishzxf** [comment]
> 为了支持同一个路由多个Tab，页面路由是以fullpath为key的，所以不同的查询参数会触发页面文件重新渲染 对于你来说，重新执行了onMounted也没问题，就相当于是刷新了页面一样

我有一个需求：
有一个页面上有多个 tabs，不管我在哪个 tab，需要刷新页面后还是在这个 tab，或者从跳出的页面跳回来的时候还是当前的 tab。我想到可以使用 vue-router 的 querystring 来做，但是现在遇到问题了：
我每次切换 tab 时，使用 vue-router 修改了 querystring，页面都重新加载了，是整个标签页重新加载了，跟我按了 F5 一样，这不是我想要的，我只是要简单切换一下 tab 而已，页面一刷新，我全部资源要重新加载，有分页表格的页面也是一样的问题，想用 querystring 保存当前页面的分页数据，但是只要切换页码，页面就刷新了，这太难受了

请问作者有什么解决方案吗？

**Comment by flyingfishzxf** [comment]
> > > 为了支持同一个路由多个Tab，页面路由是以fullpath为key的，所以不同的查询参数会触发页面文件重新渲染 对于你来说，重新执行了onMounted也没问题，就相当于是刷新了页面一样
> > 
> > 
> > 我有一个需求： 有一个页面上有多个 tabs，不管我在哪个 tab，需要刷新页面后还是在这个 tab，或者从跳出的页面跳回来的时候还是当前的 tab。我想到可以使用 vue-router 的 querystring 来做，但是现在遇到问题了： 我每次切换 tab 时，使用 vue-router 修改了 querystring，有 tabs 的页面都重新加载了，包括它下面的所有 tab 里面的子组件，这不是我想要的，我只是要简单切换一下 tab 而已，页面一刷新，我全部资源要重新加载，有分页表格的页面也是一样的问题，想用 querystring 保存当前页面的分页数据，但是只要切换页码，页面就刷新了，这太难受了
> > 请问作者有什么解决方案吗？
> 
> 首先页面的路由key得换成路由路径, 非fullPath ，然后页面路径相同，查询参数不同，默认会覆盖，只会有一个tab，如果需要多个共存，则使用multi属性

谢谢，我试试
