### ISSUE TITLE
微薄之力：应该是zh-cn

### ISSUE THREAD

**Issue by zhangYHBox** [honghuangdc/soybean-admin#267]
![image](https://github.com/honghuangdc/soybean-admin/assets/32611410/2d44ce41-e675-4820-8130-eccc63919c96)

**Comment by honghuangdc** [comment]
看一下远程的代码，是 zh-CN的，由于语言文件的特殊性，需要适配 i18n-ally插件，所以文件名称由 zh-cn变成了zh-CN

**Comment by zhangYHBox** [comment]
是我校验远程代码
