### ISSUE TITLE
[Bug]: 本地dev项目登录成功但路由未正确跳转

### ISSUE THREAD

**Issue by snowords** [honghuangdc/soybean-admin#273]
### 软件版本

0.10.3

### 运行环境

Windows (64)

### 运行架构

None

### 重现步骤

1. 拉取代码
2. pnpm dev 启动
3. 打开项目, 点击登录按钮
4. 无报错, 提示登录成功, 页面地址由`http://localhost:3200/login/pwd-login?redirect=/dashboard/analysis`变为`http://localhost:3200/dashboard/analysis`, 但是路由未正确跳转
5. 此时不进行任何操作, 刷新页面就可以正常跳转

![image](https://github.com/honghuangdc/soybean-admin/assets/22708432/9bce25f5-ce8e-4a86-93cc-9cb4a78b1f0d)

### 期望的结果是什么？
无报错, 提示登录成功, 路由正确跳转

### 实际的结果是什么？
路由未正确跳转

**Comment by honghuangdc** [comment]
能否给出一定复现的过程
可能本地开发时热更新导致数据丢失引起的
