### ISSUE TITLE
[Bug]: 当路由命名为包含关系时会导致导航菜单获取到错误的数据

### ISSUE THREAD

**Issue by Particaly** [honghuangdc/soybean-admin#279]
### 软件版本

*

### 运行环境

Windows (64)

### 运行架构

None

### 重现步骤

当顶级路由出现类似 A(route)和B(route-others)的类似命名时，目前导航组件获取的数据匹配规则是includes，这有可能会导致获取到的路由数据是错误的

### 期望的结果是什么？

依据当前路由信息严格匹配，再反查出顶级路由，根据顶级路由获取对应的导航菜单数据

### 实际的结果是什么？

未正确获取导航数据

**Comment by honghuangdc** [comment]
能给个重现步骤里面的菜单数据吗

**Comment by Particaly** [comment]
例如
```javascript
// src/router/modules/management.ts
export default {
  name: 'management',
  path: '/management',
  component: 'basic',
  meta: {
    title: '系统管理',
    i18nTitle: 'message.routes.management._value',
    icon: 'carbon:cloud-service-management',
    order: 9
  },
  children: [//children routes of management...]
}

// src/router/modules/management-special.ts
export default {
  name: 'management',
  path: '/management',
  component: 'basic',
  meta: {
    title: '系统管理',
    i18nTitle: 'message.routes.management._value',
    icon: 'carbon:cloud-service-management',
    order: 9
  },
  children: [//children routes of management-special...]
}
```
![image](https://github.com/honghuangdc/soybean-admin/assets/28535489/e3da671a-4904-4cf8-b171-6dbe60d6441b)

![image](https://github.com/honghuangdc/soybean-admin/assets/28535489/2083456e-43bf-4db7-898a-df3d3a4ae0db)
此时，点击左侧菜单栏，不会自动收起，上方菜单栏获取到的数据是management的数据
