### ISSUE TITLE
一点小建议：获取验证码按钮显示倒计时后刷新页面保留倒计时状态

### ISSUE THREAD

**Issue by wjw020206** [honghuangdc/soybean-admin#281]
### 软件版本

0.10.4

### 运行环境

Windows (64)

### 重现步骤

点击获取验证码后显示倒计时，但是刷新页面后倒计时就消失了并且可以再次点击获取验证码按钮，能不能刷新页面后倒计时的状态依旧保留

### 期望的结果是什么？

点击获取验证码后显示倒计时，刷新页面依旧接着显示倒计时

### 实际的结果是什么？

点击获取验证码后显示倒计时，刷新页面后不显示倒计时并依旧可以触发获取验证码的请求

**Comment by honghuangdc** [comment]
对接实际业务逻辑时最好通过后端返回倒计时的值

**Comment by honghuangdc** [comment]
目前前端只是个示例

**Comment by wjw020206** [comment]
> 对接实际业务逻辑时最好通过后端返回倒计时的值

好的，谢谢大佬的回复
