### ISSUE TITLE
pnpm commit 结束提示错误之后 有时候会把写好的代码全部还原，新建的文件会被删掉

### ISSUE THREAD

**Issue by yeardlry** [honghuangdc/soybean-admin#284]
pnpm commit 结束提示错误之后 有时候会把写好的代码全部还原，新建的文件会被删掉。

这个不是必现的，不知道怎么回事

**Comment by honghuangdc** [comment]
请给出复现路径

**Comment by firmianaQ** [comment]
@yeardlry  是暂存了，[git stash ]( https://git-scm.com/docs/git-stash)
