### ISSUE TITLE
如果想在全局缓存一些数据，应该在那个组件下完成

### ISSUE THREAD

**Issue by dodu2014** [honghuangdc/soybean-admin#288]
非常不错的 admin 项目，想问下作者，如果想在全局缓存一些数据，应该在那个组件下完成呢？

**Comment by honghuangdc** [comment]
你是指在本地缓存数据还是指什么，最好给出具体的业务含义

**Comment by dodu2014** [comment]
是的，我是说在业务层面，比如想把一些通用配置或者通用数据缓存的时候，最好应该在那个环节缓存呢。比如 global-content，basic-layout 或者 app-loading，还是自己新建一个 store 合适呢。

**Comment by honghuangdc** [comment]
通用的状态可以放到appStore里面
