### ISSUE TITLE
[Bug]: pre-commit 会检查所有文件,是不是应该只用 lint-staged?

### ISSUE THREAD

**Issue by firmianaQ** [honghuangdc/soybean-admin#290]
### 软件版本

1.x

### 运行环境

Windows (64)

### 运行架构

None

### 重现步骤

提交代码

### 期望的结果是什么？

只检查提交的文件

### 实际的结果是什么？

检查所有文件

**Comment by honghuangdc** [comment]
pre-commit是git的钩子函数，和lint-staged没关系，检查所有文件是因为调用了typecheck命令
