### ISSUE TITLE
[Bug]: 官网无法显示

### ISSUE THREAD

**Issue by southliu** [honghuangdc/soybean-admin#291]
### 软件版本

1.0

### 运行环境

Windows (64)

### 运行架构

None

### 重现步骤

![image](https://github.com/honghuangdc/soybean-admin/assets/26358837/1e6d0572-50c8-452a-b75b-dd9354aa78f1)
官网无法显示：https://admin.soybeanjs.cn/

### 期望的结果是什么？

正常显示

### 实际的结果是什么？

无法进入官网

**Comment by honghuangdc** [comment]
强制刷新下
