### ISSUE TITLE
beta1.0版本登录成功后notification框持续时间过长

### ISSUE THREAD

**Issue by Azir-11** [honghuangdc/soybean-admin#293]
在登录成功后会弹出一个欢迎回来的notification框，但是它没有设置自动关闭时间，这就导致了每次重新登录都需要额外的点击关闭一次这个提示性的框框，对于某些登录态不能长时间保存的应用来说，用户体验也许会更糟糕，可否考虑增加一个持续时间？

**Comment by honghuangdc** [comment]
naiveUI版本是在antd版本的基础上迁移的，antd-vue的notification组件默认不传递是会默认关闭掉的，加个延迟时间就行
