### ISSUE TITLE
[Bug]: echarts.ts如何监听折线图或者柱状图的点击事件

### ISSUE THREAD

**Issue by 593496637** [honghuangdc/soybean-admin#296]
### 软件版本

main

### 运行环境

MacOS

### 运行架构

AMD64

### 重现步骤

echarts.ts如何监听折线图或者柱状图的点击事件

### 期望的结果是什么？

可以点击柱状图并做一些操作

### 实际的结果是什么？

没有找到该功能

**Comment by honghuangdc** [comment]
[echarts文档](https://echarts.apache.org/handbook/zh/concepts/event)
