### ISSUE TITLE
[Bug]: 演示站无法访问

### ISSUE THREAD

**Issue by feacx** [honghuangdc/soybean-admin#297]
### 软件版本

online

### 运行环境

Windows (64)

### 运行架构

ARM [32] (别名：AArch32 / ARMv7）

### 重现步骤

打不开演示站，已经好久啦

### 期望的结果是什么？

恢复访问

### 实际的结果是什么？

-

**Comment by honghuangdc** [comment]
需要强制刷新下：ctr + shift + R
