### ISSUE TITLE
dev 运行报错

### ISSUE THREAD

**Issue by dodu2014** [honghuangdc/soybean-admin#307]
我这边拉下来，dev后，报错，请问是什么情况

![image](https://github.com/honghuangdc/soybean-admin/assets/15245544/6b93945a-e2e4-45e1-8bba-2a3be62eb905)

分支：main

环境：
```
PS C:\Users\dodu> node -v
v18.16.0
PS C:\Users\dodu> npm -v
8.19.4
PS C:\Users\dodu> pnpm -v
7.33.6
```

**Comment by dodu2014** [comment]
我是先fork了一份，从我的仓储拉下来的，这样报错，而直接clone你的仓储，没有报错，很是奇怪。。。。 😒😒

**Comment by gaojiangtao-git** [comment]
刚才重新down下来没问题，你可以删掉依赖试试

**Comment by honghuangdc** [comment]
> 我是先fork了一份，从我的仓储拉下来的，这样报错，而直接clone你的仓储，没有报错，很是奇怪。。。。 😒😒

你看项目哪里引用了vue-demi

**Comment by dodu2014** [comment]
@gaojiangtao-git node_modules 删掉试过n遍了，不行

**Comment by dodu2014** [comment]
> > 我是先fork了一份，从我的仓储拉下来的，这样报错，而直接clone你的仓储，没有报错，很是奇怪。。。。 😒😒
> 
> 你看项目哪里引用了vue-demi

![image](https://github.com/honghuangdc/soybean-admin/assets/15245544/0ef11b4f-da33-477d-862d-042945c758dd)

@honghuangdc  搜索了一下，貌似没有被其他地方引用，只有 pnpm-lock 文件中有这个

**Comment by honghuangdc** [comment]
> > > 我是先fork了一份，从我的仓储拉下来的，这样报错，而直接clone你的仓储，没有报错，很是奇怪。。。。 😒😒
> 
> > 
> 
> > 你看项目哪里引用了vue-demi
> 
> 
> 
> ![image](https://github.com/honghuangdc/soybean-admin/assets/15245544/0ef11b4f-da33-477d-862d-042945c758dd)
> 
> 
> 
> @honghuangdc  搜索了一下，貌似没有被其他地方引用，只有 pnpm-lock 文件中有这个

点进去，看vue-demi属于哪个依赖下的

**Comment by dodu2014** [comment]
> > > > 我是先fork了一份，从我的仓储拉下来的，这样报错，而直接clone你的仓储，没有报错，很是奇怪。。。。 😒😒
> > 
> > 
> > > 
> > 
> > 
> > > 你看项目哪里引用了vue-demi
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/15245544/300654249-0ef11b4f-da33-477d-862d-042945c758dd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY1Nzk5NjYsIm5iZiI6MTcwNjU3OTY2NiwicGF0aCI6Ii8xNTI0NTU0NC8zMDA2NTQyNDktMGVmMTFiNGYtZGEzMy00NzdkLTg2MmQtMDQyOTQ1Yzc1OGRkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTMwVDAxNTQyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdjMGJlNGI0YjU3MmViODBkZThjMjc4ODBkODk3NGU4ZWExZDUzMWQxZGQxMmRkM2ViZGE0MGNkMjU3MGE4NGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZCZD0em6icIoiqgjLEWHrnr0mqPEzGsumQGOu76dJ2U)
> > @honghuangdc  搜索了一下，貌似没有被其他地方引用，只有 pnpm-lock 文件中有这个
> 
> 点进去，看vue-demi属于哪个依赖下的

/@vueuse/core@10.7.2(vue@3.4.15):
/@vueuse/shared@10.7.2(vue@3.4.15):
/@vueuse/integrations@10.7.2(focus-trap@7.5.4)(vue@3.4.15):
/pinia@2.1.7(typescript@5.3.3)(vue@3.4.15):

这几个地方

**Comment by dodu2014** [comment]
@honghuangdc 
![image](https://github.com/honghuangdc/soybean-admin/assets/15245544/a6fa5e42-a790-4acc-91a0-77ae47d93069)

dev后，这个文件被修改，我记得在之前的版本中，components.d.ts 文件被git忽略，这个有影响吗

**Comment by honghuangdc** [comment]
没影响

**Comment by dodu2014** [comment]
![image](https://github.com/honghuangdc/soybean-admin/assets/15245544/76e82b76-9cd6-463f-a697-dede2ea186e3)

fork 的也是最新的呀，不知道为什么报错

**Comment by honghuangdc** [comment]
你这是从gitee上fork的？
