### ISSUE TITLE
[Bug], 路由开启 keepAlive, 不生效。组件的 defineOptions 未注入

### ISSUE THREAD

**Issue by AuYuHui** [honghuangdc/soybean-admin#309]
使用的是 Main 分支的代码，没有任何改动。

![image](https://github.com/honghuangdc/soybean-admin/assets/38815121/d480910c-2699-40dd-8d0d-13c4cbc17d20)
![image](https://github.com/honghuangdc/soybean-admin/assets/38815121/87a26667-c5cc-434c-b6fe-026ff2ec784e)

**Comment by honghuangdc** [comment]
已修复 [13001bc](https://github.com/honghuangdc/soybean-admin/commit/13001bc83e851350118e5621c58892ed081122cb)
