### ISSUE TITLE
路由懒加载怎么改

### ISSUE THREAD

**Issue by yezhugongjue** [honghuangdc/soybean-admin#32]
![image](https://user-images.githubusercontent.com/20020869/147841913-f1ee243e-f1be-44d6-9bdb-3d6d3d102366.png)

看到楼主的 封装了 挺规范 ，问下路由懒加载怎么弄
顺便新年顶个人气

**Comment by honghuangdc** [comment]
下一版加了动态权限路由，懒加载一并集成
