### ISSUE TITLE
打包的时候报错，请问是什么原因呢？

### ISSUE THREAD

**Issue by a-goer** [honghuangdc/soybean-admin#35]
![image](https://user-images.githubusercontent.com/43976630/150093144-a78083e5-79bc-42f3-8018-a849cc9e1dc8.png)

**Comment by honghuangdc** [comment]
你执行一下 pnpm vtsc && vite build 试试看，
这错误里面提到是npm的问题

**Comment by a-goer** [comment]
试了，还是报一样的错
![image](https://user-images.githubusercontent.com/43976630/150292521-85bbb578-b2bf-4cd9-b7b3-a418737b2b68.png)

**Comment by a-goer** [comment]
估计是我的node版本问题，我的是13.X
