### ISSUE TITLE
增加ifarme共用布局页面功能的建议

### ISSUE THREAD

**Issue by lixinliA** [honghuangdc/soybean-admin#44]
在实际应用中如果系统包含多个ifarme，并且ifarme的地址由使用者自定义，遇到这样的业务流程，目前系统这样的方式就无法满足。希望作者可以增加ifarme公用布局组件的功能。感谢

**Comment by honghuangdc** [comment]
目前大致想了一下，还不是很好实现

**Comment by honghuangdc** [comment]
已经排计划实现全局Iframe组件了

**Comment by honghuangdc** [comment]
安排在 v2.0 #188
