### ISSUE TITLE
一点小建议

### ISSUE THREAD

**Issue by lixinliA** [honghuangdc/soybean-admin#47]
系统要用起来,菜单管理是必须的基础,是不是该着重实现一下菜单的管理,哪怕不对接接口,只是提供一个添加一级,多级菜单,外链和iframe，按钮的例子,这样使用的人能按照模板去自己实现接口的对接,系统也能更好的用起来

**Comment by honghuangdc** [comment]
单纯的前端的菜单管理的涉及稍微复杂点，这个得好好地考虑一下
