### ISSUE TITLE
多标签栏不会自适应

### ISSUE THREAD

**Issue by yanbowe** [honghuangdc/soybean-admin#5]
![image](https://user-images.githubusercontent.com/43030980/138814048-7fee2fc6-5742-4760-885c-974da7030a67.png)
在电脑屏幕比较小的时候应该出现如下图所示出现滚动条和切换箭头
![image](https://user-images.githubusercontent.com/43030980/138814213-776bd336-8796-42df-b164-ac7931a9883c.png)

**Comment by honghuangdc** [comment]
已经修复了，暂时用左右滑动的方式代替
