### ISSUE TITLE
建议增加对tabs的操作和锁屏的功能

### ISSUE THREAD

**Issue by zzutligang** [honghuangdc/soybean-admin#50]
对tabs的操作，例如关闭所有，关闭其他，关闭当前等。另外锁屏现在也挺流行的，建议加锁屏的功能

**Comment by honghuangdc** [comment]
tab操作少了一个关闭所有，锁屏功能后面会考虑一下

**Comment by heii** [comment]
多页签过多超出时，能够增加用鼠标滚轮滚动吗？

**Comment by honghuangdc** [comment]
大多数鼠标滚轮都是上下滑动的，现在的多页签用鼠标左右拖拽就行了

**Comment by honghuangdc** [comment]
> 

大多数鼠标滚轮都是上下滑动的，现在的多页签用鼠标左右拖拽就行了

**Comment by honghuangdc** [comment]
> 对tabs的操作，例如关闭所有，关闭其他，关闭当前等。另外锁屏现在也挺流行的，建议加锁屏的功能

锁屏功能已经排计划了

**Comment by honghuangdc** [comment]
锁屏组件先不做了
