### ISSUE TITLE
对于菜单管理 有无计划？

### ISSUE THREAD

**Issue by bytegolang** [honghuangdc/soybean-admin#53]
对于菜单管理 有无计划？
另外建议，增加 readmap.md 开发路线图，类似下图：
![微信截图_20220301094337](https://user-images.githubusercontent.com/16700482/156088968-d9c594e8-8af1-49a5-86ec-4e7623ba8ef0.png)

建议：增加类似下图的布局
![image](https://user-images.githubusercontent.com/16700482/156093729-aa9fd6d1-8cc3-44e9-87f5-90c8aa8e1047.png)

**Comment by honghuangdc** [comment]
> 对于菜单管理 有无计划？ 另外建议，增加 readmap.md 开发路线图，类似下图： ![微信截图_20220301094337](https://user-images.githubusercontent.com/16700482/156088968-d9c594e8-8af1-49a5-86ec-4e7623ba8ef0.png)
> 
> 建议：增加类似下图的布局 ![image](https://user-images.githubusercontent.com/16700482/156093729-aa9fd6d1-8cc3-44e9-87f5-90c8aa8e1047.png)

前端的菜单管理暂时没有计划
这个布局和内置的左侧菜单混合模式有什么不同，有没有示例链接

**Comment by bytegolang** [comment]
head的宽度是 100%

**Comment by bytegolang** [comment]
> 内置的 左侧菜单混合模式的 侧边栏高度是 100%
> 
> 建议新增的是： head的宽度是 100% 侧边栏的高度 是 100%-head的height

内置的 左侧菜单混合模式的 侧边栏高度是 100%

建议新增的是：
head的宽度是 100%
侧边栏的高度 是 100%-head的height

**Comment by bytegolang** [comment]
> > 对于菜单管理 有无计划？ 另外建议，增加 readmap.md 开发路线图，类似下图： ![微信截图_20220301094337](https://user-images.githubusercontent.com/16700482/156088968-d9c594e8-8af1-49a5-86ec-4e7623ba8ef0.png)
> > 建议：增加类似下图的布局 ![image](https://user-images.githubusercontent.com/16700482/156093729-aa9fd6d1-8cc3-44e9-87f5-90c8aa8e1047.png)
> 
> 前端的菜单管理暂时没有计划 这个布局和内置的左侧菜单混合模式有什么不同，有没有示例链接

内置的 左侧菜单混合模式的 侧边栏高度是 100%

建议新增的是：
head的宽度是 100%
侧边栏的高度 是 100%-head的height

**Comment by honghuangdc** [comment]
昨天已经排计划了

**Comment by ischenxin** [comment]
rbac管理是否也在计划中呢

> 昨天已经排计划了

**Comment by honghuangdc** [comment]
目前系统的设计只有路由管理，菜单数据由路由数据转换而成。
安排在 v2.0 #188 实现功能丰富的路由管理。
