### ISSUE TITLE
一点疑惑

### ISSUE THREAD

**Issue by HanHuiOnLine** [honghuangdc/soybean-admin#55]
一般后台管理系统会基于一个主流的UI库（类似Elment-Plus这样的）。
这样的话，使用者在使用后台的过程中，更好的修改一些东西达到自己的要求。
不知道作者后面要做成什么样的一个后台管理系统呢，
使用者能否基于这个系统，构建出符合自己要求的系统呢？

**Comment by honghuangdc** [comment]
也会有其他UI库版本的。该项目专注将一些路由配置、权限配置、菜单配置、多页签配置、主题配置和请求封装做好，还有代码规范，以便进行二次开发。至于二次开发成后台管理还是PC系统都可以。
