### ISSUE TITLE
bug：[vite] Internal server error: Icon mdi:close not found   

### ISSUE THREAD

**Issue by zhanglijie5997** [honghuangdc/soybean-admin#57]
hi， 我又遇到了问题， [vite] Internal server error: Icon mdi:close not found  这个是网络的问题还是 ？

**Comment by honghuangdc** [comment]
这个问题也是node版本的问题

**Comment by honghuangdc** [comment]
node升级了多少的版本了

**Comment by zhanglijie5997** [comment]
<img width="691" alt="image" src="https://user-images.githubusercontent.com/42401363/156729712-999c354f-4563-41a2-b941-d559f115c88d.png">
最低支持的node版本是多少啊😅

**Comment by zhanglijie5997** [comment]
ok了，用最新版的node😅

**Comment by honghuangdc** [comment]
> ok了，用最新版的node😅

帮忙star一下项目
