### ISSUE TITLE
关于页面滚动

### ISSUE THREAD

**Issue by coder-chin** [honghuangdc/soybean-admin#59]
https://github.com/TuSimple/naive-ui/issues/2556 
你提的这个issue打算咋办啊？ 还挺感兴趣的，不知道打算咋解决

**Comment by honghuangdc** [comment]
就是监听组件的可见属性，然后给body添加overflow: hidden; 和padding

**Comment by honghuangdc** [comment]
项目里面有在外部添加: src/store/subscribe/app
