### ISSUE TITLE
建议: 个人封装的组件位置

### ISSUE THREAD

**Issue by YanzyUpEveryDay** [honghuangdc/soybean-admin#60]
个人建议 项目自身封装的组件还是放在自身项目里，避免使用者有部分重写的需求时，操作不便。例如： 目前layout 和 tab

**Comment by yanbowe** [comment]
> 个人建议 项目自身封装的组件还是放在自身项目里，避免使用者有部分重写的需求时，操作不便。例如： 目前layout 和 tab

可以把相关源码克隆下来修改

**Comment by honghuangdc** [comment]
> 个人建议 项目自身封装的组件还是放在自身项目里，避免使用者有部分重写的需求时，操作不便。例如： 目前layout 和 tab

这些组件都是开源的，可以自己改或者提pr
