### ISSUE TITLE
菜单图标使用本地svg

### ISSUE THREAD

**Issue by chenbj2333** [honghuangdc/soybean-admin#61]
你好，对于菜单图标使用本地svg图片有没有什么解决方案？

**Comment by honghuangdc** [comment]
目前还不支持本地svg图表动态渲染，后面我想想办法

**Comment by honghuangdc** [comment]
目前主要是用unplugin-icons这个插件实现的iconify图表和本地svg转成iconify图表

**Comment by chenbj2333** [comment]
> 目前还不支持本地svg图表动态渲染，后面我想想办法

好的，谢谢回复。因为我这边是内网开发，所以会有这个问题。那可以把iconify这个库放在本地用吗？（我不是很了解这块）

**Comment by honghuangdc** [comment]
iconify主要是去请求json数据，可以用外网把依赖复制进项目，应该就可以了

**Comment by chenbj2333** [comment]
> iconify主要是去请求json数据，可以用外网把依赖复制进项目，应该就可以了

好的，我去试试，谢谢～

**Comment by tclyjy** [comment]
> iconify主要是去请求json数据，可以用外网把依赖复制进项目，应该就可以了

SVG sprite 方案你觉得如何？我尝试使用vite-plugin-svg-icons 解决了这个问题

**Comment by tclyjy** [comment]
> 可以是可以，其实这个插件最早有伙伴实现了，后来又被我去掉了，我想要和现有的iconify图标的使用方法尽量保持一致，你可以先试试，然后要有对应的组件类型

你的想法是对的
