### ISSUE TITLE
多页签切换点击无法保存路由中的query参数

### ISSUE THREAD

**Issue by vany810** [honghuangdc/soybean-admin#64]
路由中有查询参数比如/book?bookId=123,在多页签切换到其它页面再切换回来，会丢失路由的查询条件

**Comment by baiye0** [comment]
@honghuangdc  需要做吗？ 需要我可以做一下，然后pr一下。

**Comment by honghuangdc** [comment]
当然可以😄，欢迎欢迎

**Comment by baiye0** [comment]
> 当然可以😄，欢迎欢迎

好，我试试 😁
