### ISSUE TITLE
顶部菜单功能建议

### ISSUE THREAD

**Issue by sunviv** [honghuangdc/soybean-admin#68]
建议增加如图所示功能，菜单显示不开增加更多项展示
![image](https://user-images.githubusercontent.com/74650847/159855685-5c63f581-5ff1-4789-9b55-2b64b9b9d8b1.png)

**Comment by honghuangdc** [comment]
这个需要naiveUI的菜单组件有这个功能，很久之前向naiveUI提过这个建议
