### ISSUE TITLE
Icon依赖优化

### ISSUE THREAD

**Issue by yanbowe** [honghuangdc/soybean-admin#7]
![image](https://user-images.githubusercontent.com/43030980/140602556-1aacfa07-0532-4547-b71e-338392237fc7.png)
为什么会引入这么多的icons插件，导致安装依赖特别大，是不是有些冗余呢

**Comment by honghuangdc** [comment]
naiveUI的图标组件是基于vicons，所以引入了这么多vicons。

**Comment by honghuangdc** [comment]
iconify这个很好用，所以保留下来了，我后面想办法优化一下

**Comment by honghuangdc** [comment]
或者你安装依赖的时候，可以设置npm为国内镜像加速下载，设置github代理，加速github代码访问速度

**Comment by yanbowe** [comment]
> naiveUI的图标组件是基于vicons，所以引入了这么多vicons。

其实一个@vicons/antd就满足现有图标需求了吧

**Comment by yanbowe** [comment]
> 或者你安装依赖的时候，可以设置npm为国内镜像加速下载，设置github代理，加速github代码访问速度

现在安装依赖确实很慢，大概需要5分钟的时间

**Comment by honghuangdc** [comment]
用pnpm安装也很慢吗，这个npm包管理器是全局共享依赖的，安装过一次后就不需要安装了，除非变更版本。

**Comment by honghuangdc** [comment]
我这边每次安装都很快的，你看一下是不是系统的环境有些问题

**Comment by honghuangdc** [comment]
已经统一了图标用法，去除了vicons，见文档：https://github.com/honghuangdc/soybean-admin/blob/main/doc/iconify%E4%BD%BF%E7%94%A8%E6%96%87%E6%A1%A3.md

**Comment by yanbowe** [comment]
> 我这边每次安装都很快的，你看一下是不是系统的环境有些问题

我每次都是删除node_modules安装的，会比较慢，或许和我的网络环境有关。

**Comment by yanbowe** [comment]
> 已经统一了图标用法，去除了vicons，见文档：https://github.com/honghuangdc/soybean-admin/blob/main/doc/iconify%E4%BD%BF%E7%94%A8%E6%96%87%E6%A1%A3.md

现在依赖确实少了很多，点赞
