### ISSUE TITLE
post请求在网络中可以看到后端正确返回信息，但是consol终端打印返回信息为空。

### ISSUE THREAD

**Issue by yangsadd** [honghuangdc/soybean-admin#73]
网络请求返回为 
{
  "status": 200,
  "data": {
    "user": {
      "name": "dfhndfs",
      "age": "dfgndftgs"
    },
    "phone": "dfthnde"
  },
  "msg": "success",
  "error": null
}
consol打印结果为
{
    "error": {
        "type": "backend"
    },
    "data": null
}

**Comment by honghuangdc** [comment]
需要配置前后端的数据结构字段统一，在service/request/instance里面配置backendConfig，默认的是 codeKey: 'code',dataKey: 'data',msgKey: 'message',successCode: 200, 也就是 { code, data, message }的结构

**Comment by yangsadd** [comment]
按照instance 的字段构造api返回数据结构成 
return {"code": "test", "data": ret, "message": ret, "successCode": 200}.
网络返回数据为
 {"code":"test","data":[{"_id":2,"name":"菠萝","age":10}],"message":"here is mesage","successCode":200}
但是res打印出来是 
{"error":{"type":"backend","code":"test","msg":"here is mesage"},"data":null}
T.T

**Comment by yangsadd** [comment]
好了，我把变量名从ret 换成data 也就是
return {"code": "test", "data": data, "message": "here is mesage", "successCode": 200}.
居然就可以了 ）

**Comment by yangsadd** [comment]
万分感谢大佬！！！！！！！！！！！！！！
