### ISSUE TITLE
固定路由怎么加？

### ISSUE THREAD

**Issue by zhaozhuangwang** [honghuangdc/soybean-admin#74]
接触vue3 还不熟悉，后端是ruoyi，前台想用一下这个ui，发现了这个admin, 

从登陆获取mock数据，加载动态路由，但是我需要几个固定路由无需登录，修改了 guard 还有 route, 发现要不还有些地方限制，要不就是逻辑报错了，请问怎么增加？

**Comment by zhaozhuangwang** [comment]
> src/router/routes/index.ts => constantRoutes,这个是固定路由

我改过了，不行， guard routes 两个文件夹都 试了的，

而且 我说的固定路由要在系统内，不是登录页面那种，在外层

你可以给个参考么？

**Comment by honghuangdc** [comment]
我的意思是固定路由的数据就是放到src/router/routes/index.ts => constantRoutes里面的，至于你想要什么这个路由什么布局，自己再写对应布局的路由数据，先参照一下文档的路由这一块的说明。

**Comment by zhaozhuangwang** [comment]
行吧 ， 谢谢了
