### ISSUE TITLE
上下结构，菜单建议加个横向滚动

### ISSUE THREAD

**Issue by ChasonHong** [honghuangdc/soybean-admin#76]
建议上下结构鼠标移入时，显示横向滚动条，如下图：
<img width="1011" alt="截屏2022-04-19 18 45 57" src="https://user-images.githubusercontent.com/11606876/163987599-41f6d8d9-c420-4f35-ab33-2b2f97ab264f.png">

**Comment by honghuangdc** [comment]
https://www.antdv.com/components/menu-cn/#Menu-
给官方提了这个建议：类似于antd的menu组件，容器宽度很小时就隐藏，显示缩略号
