### ISSUE TITLE
会有表格，表单以及常用组件的封装吗？

### ISSUE THREAD

**Issue by yanbowe** [honghuangdc/soybean-admin#8]
期望增加一些后台管理的常用组件，例如全局搜索菜单，表格以及表单之类的封装

**Comment by honghuangdc** [comment]
会有的，我接下来就是要添加常用的插件。

**Comment by yanbowe** [comment]
> 会有的，我接下来就是要添加常用的插件。

期待，很喜欢您的代码风格

**Comment by a-goer** [comment]
打包的时候报错
![image](https://user-images.githubusercontent.com/43976630/150092517-f5a45f71-967b-4035-b1e8-8a40f054290d.png)
