### ISSUE TITLE
左边菜单，加一个深色背景的颜色风格切换吧！

### ISSUE THREAD

**Issue by mx4g** [honghuangdc/soybean-admin#80]
你好呀！加一个左边菜单背景颜色切换的功能吧！全部都是白色有些单调！
类似这个颜色，左边能有个黑色内饰：
![image](https://user-images.githubusercontent.com/7499986/165262865-013bf6f4-3a03-48fd-8970-0c3a6b3a7b5f.png)

**Comment by honghuangdc** [comment]
可以的

**Comment by mx4g** [comment]
> 

谢谢！
