### ISSUE TITLE
多标签优化

### ISSUE THREAD

**Issue by yanbowe** [honghuangdc/soybean-admin#9]
![image](https://user-images.githubusercontent.com/43030980/140707568-3a23df59-4621-43a1-bfd6-ea284ee54fd8.png)
点击关闭标签页的时候，关闭掉的并不是右键所选中的标签页，所以不在当前页的时候关闭标签页应该禁用吧

**Comment by honghuangdc** [comment]
嗯嗯，这个是个bug，我晚点改一下。

**Comment by yanbowe** [comment]
> 嗯嗯，这个是个bug，我晚点改一下。

可否顺便增加个关闭左侧和关闭右侧呢

**Comment by honghuangdc** [comment]
已经修复了，关闭左侧和右侧也加了
