### ISSUE TITLE
createHookRequest函数示例

### ISSUE THREAD

**Issue by FeiFanLiang** [honghuangdc/soybean-admin#90]
看了大佬的项目，对于`createHookRequest`函数有一点疑惑，
这个函数应该是一个基于hook的请求方法，使用调用之后返回的`get`,`post`等方法进行请求，会自动进行loading状态和是否网络在线状态的更新。
在组件内，如果想直接使用方法返回的loading状态，如分页加载时的loading状态，每次发起请求时都会返回新的loading，貌似并不能够直接利用返回的loading，还是要在组件内自己维护一个loading。不知道大佬能否提供一个组件内使用的示例呢？

**Comment by honghuangdc** [comment]
你说的这种场景应该不适合用createHookRequest

**Comment by honghuangdc** [comment]
直接用自己创建的loading状态，调用接口前开始加载，请求结束后结束加载
