### ISSUE TITLE
本地开发模式，热更新失效问题

### ISSUE THREAD

**Issue by FeiFanLiang** [honghuangdc/soybean-admin#94]
进行路由添加或页面代码修改时，浏览器会一直处于loading状态，点击其他页签tab也无法正常加载，必须手动刷新，请问其他人是否也出现过此类情况？

**Comment by honghuangdc** [comment]
修改路由相关的确实会有这个热更新问题😮‍💨，目前看来还是和vite相关，只能手动刷新，暂时也没有更好的办法。

**Comment by honghuangdc** [comment]
vite最新版好像没有问题了
