### ISSUE TITLE
是否考虑引入antd或arco？

### ISSUE THREAD

**Issue by cqlmq** [honghuangdc/soybean-admin#96]
naiveui 总体不错，感觉表格、表单功能需要加强，是否可以在项目里按需引入antd或arcok呢？颜色与主题能否统一？

**Comment by honghuangdc** [comment]
先把这个naiveUI的版本完善好，后面再推出其他UI的版本

**Comment by xingyu4j** [comment]
表格可以直接使用vxe-table，目前element antd naive 等几个的table都不咋的

**Comment by honghuangdc** [comment]
暂无其他UI版本的计划，有需要者自行改造
