### ISSUE TITLE
后端动态路由指定首页不生效

### ISSUE THREAD

**Issue by zxdstyle** [honghuangdc/soybean-admin#97]

**Comment by zxdstyle** [comment]
后端动态指定首页后，登录跳转、logo点击等还是跳转的 root 路由

**Comment by honghuangdc** [comment]
这个目前需要前端改一下 .env里面的 VITE_ROUTE_HOME_PATH, 后面我再看看有没有好的办法

**Comment by MartinLongYW** [comment]
请问下，假如我新增了一个test做为首页，我后端返回的home设置为test，此时登录成功后会跳转到test。但默认的首页tab还是会显示在tab栏上面。有没有方法直接把test直接替换原先首页显示的位置。
