### ISSUE TITLE
项目静置一段时间后（BUG出现场景：打开页面放着一晚上），第二天就会报错，是什么导致的。

### ISSUE THREAD

**Issue by su-yongjian** [honghuangdc/soybean-admin#98]
![1653614235(1)](https://user-images.githubusercontent.com/34278832/170609336-5f2b4212-f1bc-4759-861b-b6a8a503c933.jpg)

**Comment by yanbowe** [comment]
> ![1653614235(1)](https://user-images.githubusercontent.com/34278832/170609336-5f2b4212-f1bc-4759-861b-b6a8a503c933.jpg)

线上的情况吗？

**Comment by honghuangdc** [comment]
这个是因为我推过新代码，重新部署后，静态资源的哈希值就会变化，你本地的html有缓存，静态资源地址指向是旧的资源地址，由于部署了新版，所以旧资源不存在。
这个在开发的项目都有这个问题，需要配置不缓存html
简单的方式就是重新刷新下
